"""Added language detection

Revision ID: 4cb75ff1bddd
Revises: 0e25dc05265d
Create Date: 2020-10-05 14:47:17.429984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb75ff1bddd'
down_revision = '0e25dc05265d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'posts',
        sa.Column('lang', sa.Unicode(length=255), nullable=True)
    )
    op.add_column(
        'posts',
        sa.Column('lang_timestamp', sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'lang_timestamp')
    op.drop_column('posts', 'lang')
    # ### end Alembic commands ###
