"""Added author foreign key for blogpost

Revision ID: de3321bc2c27
Revises: 7d27902a3fb6
Create Date: 2020-09-27 15:49:34.805845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3321bc2c27'
down_revision = '7d27902a3fb6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_posts_author_users'), 'posts', 'users', ['author'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_posts_author_users'), 'posts', type_='foreignkey')
    op.drop_column('posts', 'author')
    # ### end Alembic commands ###
