"""Fixed post title being unique

Revision ID: 780ed3799394
Revises: 4cb75ff1bddd
Create Date: 2020-10-06 03:23:20.120737

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '780ed3799394'
down_revision = '4cb75ff1bddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_posts_title', table_name='posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_posts_title', 'posts', ['title'], unique=True)
    # ### end Alembic commands ###
