name: release

on:
  push:
    branches:
    - "releases/**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Setup environment
        run: |-
          python -m pip install app/blog-platform/.

      - name: Code style check
        run: |-
          . scripts/build/linting.sh

      - name: Run tests
        run: |-
          . scripts/build/testing.sh

      - name: Creating artifacts
        run: |-
          zip -r release.zip app/blog-platform

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
          with:
            name: release
            path: release.zip

  deploy:
    name: Deploy
    needs: release
    runs-on: ubuntu-latest
    env:
      - SERVER_ADDRESS: ${{ secrets.PRODUCTION_HOST }}
      - SERVER_PORT: ${{ secrets.PRODUCTION_PORT }}
      - SSH_USER: ${{ secrets.PRODUCTION_SSH_USER }}
      - SSH_KEY: ${{ secrets.PRODUCTION_SSH_KEY }}
      - SSH_PASSWORD: ${{ secrets.PRODUCTION_SSH_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get artifact
        uses: actions/download-artifact@v2
          with:
            name: release

      - name: Setup server
        run: |-
          ssh $SERVER_ADDRESS -l $SSH_USER -p $SERVER_PORT 'bash -s' < $(cat \
            scripts/deploy/2-0-setup-common.sh \
            scripts/deploy/2-1-setup-python.sh \
            scripts/deploy/2-2-setup-postgres.sh \
            scripts/deploy/2-3-setup-nginx.sh \
            scripts/deploy/3-1-setup-deployment.sh \
          )

      - name: Run pre deploy
        run: |-
          ssh $SERVER_ADDRESS -l $SSH_USER -p $SERVER_PORT 'bash -s' < $(cat \
            scripts/deploy/4-1-run-predeploy.sh \
          )

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          port: ${{ secrets.PRODUCTION_PORT }}
          username: ${{ secrets.PRODUCTION_SSH_USER }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          source: "release.zip"
          target: "/opt/kanava14/release.zip"

      - name: Deploy artifact
        run: |-
          ssh $SERVER_ADDRESS -l $SSH_USER -p $SERVER_PORT 'unzip -q -o /opt/kanava14/release.zip -d /opt/kanava14fi/blog-platform'

      - name: Running post deploy scripts
        run: |-
          ssh $SERVER_ADDRESS -l $SSH_USER -p $SERVER_PORT 'bash -s' < $(cat \
            scripts/deploy/3-2-setup-deployment-postdeploy.sh \
            scripts/deploy/4-2-run-postdeploy.sh \
          )
