name: release

on:
  push:
    branches:
    - "releases/**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Setup environment
        run: |-
          python -m pip install app/blog-platform

      - name: Code style check
        run: |-
          . scripts/build/linting.sh

      - name: Run tests
        run: |-
          . scripts/build/testing.sh

  deploy:
    name: Deploy
    # needs: release
    runs-on: ubuntu-latest
    env:
      SERVER_ADDRESS: ${{ secrets.PRODUCTION_HOST }}
      SERVER_PORT: ${{ secrets.PRODUCTION_PORT }}
      SSH_USER: ${{ secrets.PRODUCTION_SSH_USER }}
      SSH_KEY: ${{ secrets.PRODUCTION_SSH_KEY }}
      SSH_PASSWORD: ${{ secrets.PRODUCTION_SSH_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Private key setup
        run: |-
          echo -e $SSH_KEY > ./pkey && chmod 600 ./pkey

      - name: Deploy server tools
        run: |-
          rsync -e "ssh -o StrictHostKeyChecking=no -i ./pkey -p $SERVER_PORT" \
            -a scripts/deploy/ $SSH_USER@$SERVER_ADDRESS:/opt/kanava14fi/app/scripts/deploy/

      - name: Run pre deploy scripts
        run: |-
          ssh $SERVER_ADDRESS -l $SSH_USER -p $SERVER_PORT -i ./pkey -o StrictHostKeyChecking=no \
            '/bin/bash /opt/kanava14fi/app/scripts/deploy/1-master-run.sh'

      - name: Deploy to server
        run: |-
          rsync -e "ssh -o StrictHostKeyChecking=no -i ./pkey -p $SERVER_PORT" \
            -a app/blog-platform/ $SSH_USER@$SERVER_ADDRESS:/opt/kanava14fi/blog-platform/

      - name: Running post deploy scripts
        run: |-
          ssh $SERVER_ADDRESS -l $SSH_USER -p $SERVER_PORT -i ./pkey -o StrictHostKeyChecking=no \
          '/bin/bash /opt/kanava14fi/app/scripts/deploy/1-1-master-run-post-deploy.sh'
