name: release

on:
  push:
    branches:
    - "releases/**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
        run: |-
          python -m pip install app/blog-platform/.

      - name: Code style check
        run: |-
          . scripts/build/linting.sh

      - name: Run tests
        run: |-
          . scripts/build/testing.sh

      - name: Compiling
        run: |-
          echo "Compiling..."

      - name: Deploy
        run: |-
          echo "Deploying..."
